[package]
name = "avvy"
version = "0.1.0"
authors = ["Xavier Lange <xrlange@gmail.com>"]

[dependencies]
log = "0.4.3"
serde = "1.0.70"
serde_derive = "1.0.70"
serde_json = "1.0.24"
byteorder = "1.2.3"
integer-encoding = "1.0.5"

[profile.release]
lto = true

[profile.bench]
lto = true